### ISSUE TITLE
Update to latest sente version to fix CSRF vulnerability

### ISSUE THREAD

**Issue by rafd** [braidchat/braid#191]
See https://github.com/ptaoussanis/sente/blob/master/CHANGELOG.md#v1140-rc2---2019-jan-12

**Comment by jamesnvc** [comment]
I'm disabling the server-side CSRF checking right now for the setup. Since that initial call is made over ajax to another domain (websocket is on api.braid.chat, but user is on braid.chat) so that isn't really a way to get that token that isn't just as trivially hijackable. I think CORS protection should guard against this, in any case.

**Comment by jamesnvc** [comment]
Yeah, addressing #192 makes cross-site websocket starting fail, even if the csrf token is ignored for sente, which I think is okay.
